### ISSUE TITLE
Wrong repository URI in CodeLab

### ISSUE THREAD

**Issue by danizord** [firebase/friendlyeats-web#1]
Hey! In [Firestore Web Codelab - Step 2](https://codelabs.developers.google.com/codelabs/firestore-web/#1), there's the command:
`git clone sso://devrel/samples/firebase/fireeats/web fireeats -b codelab-beginning`

This URI can't be understood by my git client:
![captura de tela 2017-10-03 as 14 23 29](https://user-images.githubusercontent.com/1850941/31138947-78cb0d54-a846-11e7-9451-69c7aed57870.png)
So the URI should probably be updated to `git@github.com:firebase/friendlyeats-web.git`

**Comment by abehaskins** [comment]
Great catch, updating it now!

**Comment by abehaskins** [comment]
Fixed, thanks!

**Comment by manucho007** [comment]
the problem still exists with the new URL
![image](https://user-images.githubusercontent.com/17936451/31470170-b615fc24-aeb2-11e7-9585-926a1bbd52cc.png)
Solved this issue changing the url to
$ git clone https://github.com/firebase/friendlyeats-web.git
